version: '3.8'

services:
  pdf-analysis-system:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./Challenge_1b:/app/Challenge_1b
      - ./output:/app/output
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a simple web interface
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - pdf-analysis-system
    restart: unless-stopped 