version: '3.8'

services:
  pdf-analysis-system:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./input:/app/input
      - ./output:/app/output
      - ./Challenge_1b:/app/Challenge_1b
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 